name: Build Devcontainer

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-python@v4
      - name: Install with pip
        run: pip install -r tests/build/requirements.txt
      - name: Prepare build source directories/files
        run: python ./tests/build/prebuild.py prepare-mounts ${{ inputs.path }}/.devcontainer/devcontainer.json
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy .devcontainer/ into working directory
        run: cp -r ${{ inputs.path }}/.devcontainer/* .devcontainer || true
      - name: Trim path prefix `.`
        id: trim-dot
        run: echo "##[set-output name=suffix;]$(sed -e 's/^\.//' <<< '${{ inputs.path }}')"
      - name: Build and test zsh
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/hayas1/dotfiles${{ steps.trim-dot.outputs.suffix }}
          runCmd: ./tests/container/installed.sh
