name: Devcontainer CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and test zsh
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/hayas1/dotfiles
          runCmd: ./tests/container/installed.sh
