name: On Master CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-build:
    uses: hayas1/dotfiles/.github/workflows/devcontainer-ci.yml@master
    with:
      branch: ${{ github.ref }}
  # test-public-script:
  #   uses: hayas1/dotfiles/.github/workflows/public-script-ci.yml@master
  #   with:
  #     branch: ${{ github.ref }}
