name: Master CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    uses: hayas1/dotfiles/.github/workflows/build-devcontainer.yml@master
    with:
      branch: ${{ github.ref }}
      path: "."
  build-examples:
    strategy:
      matrix:
        devcontainer: ["./examples/clone", "./examples/features"]
    uses: hayas1/dotfiles/.github/workflows/build-devcontainer.yml@master
    if: ${{ github.event_name == 'push' }}
    with:
      branch: ${{ github.ref }}
      path: ${{ matrix.devcontainer }}
