name: On Mount CI

on:
  push:
    branches: ["mount"]

jobs:
  pr-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: create-pull-request
        run: >
          gh pr create --assignee $AUTHOR
          --title 'Auto integration to master'
          --body 'No mount setting in master branch.'
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.event.pusher.name }}
      - name: Build pull request
        uses: hayas1/dotfiles/.github/workflows/devcontainer-ci.yml@"refs/pull/$(gh pr view --json number -q .number)/merge"
      - name: Merge pull request
        id: merge-pull-request
        run: >
          gh pr merge mount --merge
          --body 'Pass build, auto merged'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
