name: Mount create PR CI

on:
  push:
    branches: ["mount"]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: create-pull-request
        run: >
          gh pr create --assignee $AUTHOR
          --title 'Auto integration to master'
          --body 'No mount setting in master branch.'
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.event.pusher.name }}
      - run: echo "${{ steps.create-pull-request.outcome }} create new pull request"
