name: Test Public Script CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  test-init-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Test public init script
        run: |
          cwd=$(pwd)
          tmp_dir=$(mktemp -dt "dotfiles.XXXXXX")
          cd $tmp_dir
          curl -fsL https://raw.githubusercontent.com/hayas1/dotfiles/master/scripts/public/init.sh | bash -s
          diff -r $cwd/.vscode $tmp_dir/.vscode
          diff -r $cwd/.devcontainer $tmp_dir/.devcontainer
  test-clean-script:
    runs-on: ubuntu-latest
    steps:
      - name: Test public clean script
        run: |
          tmp_dir=$(mktemp -dt "dotfiles.XXXXXX")
          cd $tmp_dir
          [ "$(ls -A)" ] && exit 1 # should be empty
          curl -fsL https://raw.githubusercontent.com/hayas1/dotfiles/master/scripts/public/init.sh | bash -s
          [ "$(ls -A)" ] || exit 1 # should not be empty
          tmp_dir=$(mktemp -dt "dotfiles.XXXXXX")
          curl -fsL https://raw.githubusercontent.com/hayas1/dotfiles/master/scripts/public/clean.sh > $tmp_dir/clean.sh
          chmod +x $tmp_dir/clean.sh
          [ "$(ls -A)" ] && exit 1 # should be empty
