name: Test Public Script CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  test-init-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run public init script
        id: run-init
        run: |
          curl -fsL https://raw.githubusercontent.com/hayas1/dotfiles/master/scripts/public/init.sh | bash -s
          tmp_dir=$(mktemp -dt "dotfiles.XXXXXX")
          echo "::set-output name=tmp-dir::$tmp_dir"
          mv * $tmp_dir
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Test diff directories
        run: |
          diff -r ${{ steps.run-init.outputs.tmp_dir }}/.vscode .vscode
          diff -r ${{ steps.run-init.outputs.tmp_dir }}/.devcontainer .devcontainer
  test-clean-script:
    runs-on: ubuntu-latest
    steps:
      - name: Test public clean script
        run: |
          curl -fsL https://raw.githubusercontent.com/hayas1/dotfiles/master/scripts/public/init.sh | bash -s
          [ "$(ls -A)" ] || exit 1 # should not be empty
          yes | bash <(curl -fsL https://raw.githubusercontent.com/hayas1/dotfiles/master/scripts/public/clean.sh)
          [ "$(ls -A)" ] && exit 1 # should be empty
