name: Test Public Script CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  test-init-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Test public init script
        run: |
          cwd=$(pwd)
          tmp_dir=$(mktemp -dt "dotfiles.XXXXXX")
          cd $tmp_dir
          curl -fsL https://github.com/hayas1/dotfiles/raw/master/scripts/public/init.sh | bash -s
          diff -r -x .gitignore $cwd/.vscode $tmp_dir/.vscode
          diff -r -x .gitignore $cwd/.devcontainer $tmp_dir/.devcontainer
  test-clean-script:
    runs-on: ubuntu-latest
    steps:
      - name: Test public clean script
        run: |
          tmp_dir=$(mktemp -dt "dotfiles.XXXXXX")
          cd $tmp_dir
          [ "$(ls -A)" ] && exit 1 # should be empty
          curl -fsL https://github.com/hayas1/dotfiles/raw/master/scripts/public/init.sh | bash -s
          [ "$(ls -A)" ] || exit 1 # should not be empty
          echo 'y' | bash <(curl -fsL https://github.com/hayas1/dotfiles/raw/master/scripts/public/clean.sh)
          [ "$(ls -A)" ] && exit 1 # should be empty
          ls -A
  test-install-zsh-and-prugins:
    runs-on: ubuntu-latest
    steps:
      - name: Test install zsh and plugins
        run: |
          echo $HOME
          curl -fsL https://github.com/hayas1/dotfiles/raw/master/scripts/public/docker/install-zsh-plugins.sh | bash -s
          [ "$(grep powerlevel10k ${HOME}/.zshrc)" ] || exit 1
          [ "$(grep zsh-completions ${HOME}/.zshrc)" ] || exit 1
          [ "$(grep zsh-autosuggestions ${HOME}/.zshrc)" ] || exit 1
          [ "$(grep zsh-syntax-highlighting ${HOME}/.zshrc)" ] || exit 1
          [ "$(grep zsh-history-substring-search ${HOME}/.zshrc)" ] || exit 1
