name: Test install scripts

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  INSTALL_SCRIPTS: ./public/build

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install-python
        run: sudo -E ${INSTALL_SCRIPTS}/install-python.sh && python --version && pip --version
